export const NOTES_FETCH_INIT = 'NOTES_FETCH_INIT'
export const NOTES_FETCH_SUCCESS = 'NOTES_FETCH_SUCCESS'
export const NOTES_FETCH_ERROR = 'NOTES_FETCH_ERROR'

export const NOTE_CREATE_INIT = 'NOTE_CREATE_INIT'
export const NOTE_CREATE_SUCCESS = 'NOTE_CREATE_SUCCESS'
export const NOTE_CREATE_ERROR = 'NOTE_CREATE_ERROR'

export const NOTE_UPDATE_INIT = 'NOTE_UPDATE_INIT'
export const NOTE_UPDATE_SUCCESS = 'NOTE_UPDATE_SUCCESS'
export const NOTE_UPDATE_ERROR = 'NOTE_UPDATE_ERROR'

export const NOTE_DELETE_INIT = 'NOTE_DELETE_INIT'
export const NOTE_DELETE_SUCCESS = 'NOTE_DELETE_SUCCESS'
export const NOTE_DELETE_ERROR = 'NOTE_DELETE_ERROR'

export const SET_LANGUAGE = 'LANGUAGE_SET'
